name: cone
description: A ledger-like implemented in Dart language.
# version: 1.0.0
# homepage: https://www.example.com
# author: Brady Trainor <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0

executables:
  cone: cone
