name: cone
description: A ledger-like implemented in Dart language.
version: 0.0.0
# homepage: https://www.example.com
# author: Brady Trainor <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  petitparser:

dev_dependencies:
  build_runner:
  build_version:
  test: ^1.0.0

executables:
  cone: cone
